#!/bin/bash

# This is a script for MyAnimeList forums. It takes a forum thread's url as an argument, and spits out the following 3
# numbers: the # of replies, the # of contributors (i.e., unique posters), and the total word count. It is also able to
# perform this calculation for any number of url arguments.
# Example:
# qd-wiz "http://myanimelist.net/forum/?topicid=708227" "http://myanimelist.net/forum/?topicid=708231" "http://myanimelist.net/forum/?topicid=708235"

for i in "$@"; do
    # Download the html pages.
    # maybe curl, and/or request access from xinil
    #wget -e robots=off --wait 0.25 -qO /tmp/dummy.html "$i"
    #wget -e robots=off -qO /tmp/dummy.html "$i"

    # Grab only the desired text.
    # use a html parser instead of sed
    sed -e 's/<div id=\"message[0-9]\+\">\(.*\)<\/div>/\1/' /tmp/dummy.html
    replies =
    contributors =
    wordcount =

    # Output the 3 numbers.
    print $replies $contributors $wordcount
done
